modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="vipium"
version="1.3.2"
displayName="V.I.P Mod"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/FlowArg/VIPMod"
logoFile="vip.png"
credits="Thanks Proflapoule & EngineTH3F for making all textures in this mod !"
authors="Flow Arg (FlowArg)"
description='''
This is the official mod for the V.I.P Server !
'''

[[dependencies.vipium]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vipium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
